Repository bitcashorg/masterbots, pull requests merged in 2024-02, with the labels that each got.

#16 Feat: Chat Clickable IA Responses
  apps/masterbots.ai/components/chat-list.tsx
  apps/masterbots.ai/components/chat-message.tsx
  apps/masterbots.ai/components/chat.tsx
  bun.lockb
Labels: enhancement

#23 fix: ai response on chat view
  apps/masterbots.ai/app/(chat)/[chatbot]/[threadId]/page.tsx
  apps/masterbots.ai/app/(chat)/[chatbot]/page.tsx
  apps/masterbots.ai/components/chat-accordion.tsx
  apps/masterbots.ai/components/chat.tsx
  apps/masterbots.ai/components/thread-panel/user-thread-panel.tsx
  apps/masterbots.ai/lib/hooks/use-thread.tsx
Labels: bug

#25 fix-ClickableText - Unique IA Responses
  apps/masterbots.ai/components/chat-clickable-text.tsx
Labels: bug, enhancement
