Repository bitcashorg/masterbots, pull requests merged in 2025-03, with the labels that each got.

#396 Refactor: clickable text generations logic
  apps/masterbots.ai/app/globals.css
  apps/masterbots.ai/components/routes/chat/chat-clickable-text.tsx
  apps/masterbots.ai/components/routes/chat/chat-message.tsx
  apps/masterbots.ai/lib/chat-clickable-text.tsx
  apps/masterbots.ai/lib/clickable-results.ts
  apps/masterbots.ai/lib/constants/prompts.ts
  apps/masterbots.ai/types/types.ts
Labels: bug, enhancement, difficulty:hard

#403 fix: add extra rules to clickable styles
  apps/masterbots.ai/app/globals.css
  apps/masterbots.ai/components/routes/chat/chat-message.tsx
Labels: bug, difficulty:easy

#418 Fix: deep thinking and deep reasoning state consistency
  apps/masterbots.ai/components/routes/chat/chat-combobox.tsx
  apps/masterbots.ai/components/routes/chat/chat-panel.tsx
  apps/masterbots.ai/components/routes/chat/reasoning/reasoning-chat-message.tsx
  apps/masterbots.ai/components/shared/feature-toggle.tsx
  apps/masterbots.ai/components/ui/button.tsx
  apps/masterbots.ai/lib/hooks/use-deep-thinking.tsx
  apps/masterbots.ai/lib/hooks/use-model.tsx
  apps/masterbots.ai/lib/hooks/use-power-up.tsx
Labels: bug

#422 Update Signup: Sequence-based Username, Auto-login, Email Verification
  apps/masterbots.ai/app/api/auth/signup/route.ts
  apps/masterbots.ai/components/auth/signup-form.tsx
  apps/masterbots.ai/components/routes/chat/chat-list/.index.tsx.swp
  apps/masterbots.ai/components/ui/input.tsx
  apps/masterbots.ai/lib/username.ts
  packages/mb-env/src/config.env.ts
Labels: enhancement, ui/ux, feature, backend

#424 fix: change toggler wording + util hook
  apps/masterbots.ai/components/routes/chat/chat-panel.tsx
  apps/masterbots.ai/components/routes/chat/reasoning/reasoning-chat-message.tsx
  apps/masterbots.ai/components/shared/feature-toggle.tsx
  apps/masterbots.ai/components/shared/loading-indicator.tsx
  apps/masterbots.ai/lib/hooks/use-device.tsx
Labels: bug
