Repository bitcashorg/masterbots, pull requests merged in 2025-04, with the labels that each got.

#437 feat: add gemini provider
  apps/masterbots.ai/app/actions/ai-main-call.ts
  apps/masterbots.ai/app/api/chat/models/models.ts
  apps/masterbots.ai/components/routes/chat/chat-combobox.tsx
  apps/masterbots.ai/components/ui/icons.tsx
  apps/masterbots.ai/lib/helpers/ai-helpers.ts
  apps/masterbots.ai/package.json
  apps/masterbots.ai/types/types.ts
  bun.lock
Labels: feature

#451 Fix new chats
  apps/hasura/metadata/databases/masterbots/tables/public_message.yaml
  apps/hasura/metadata/databases/masterbots/tables/public_thread.yaml
  apps/hasura/migrations/masterbots/1744868817288_alter_table_public_thread_add_column_short_link/down.sql
  apps/hasura/migrations/masterbots/1744868817288_alter_table_public_thread_add_column_short_link/up.sql
  apps/hasura/migrations/masterbots/1744868922210_alter_table_public_message_add_column_short_link/down.sql
  apps/hasura/migrations/masterbots/1744868922210_alter_table_public_message_add_column_short_link/up.sql
  apps/hasura/seeds/masterbots/1724271272084_init_threads_seeds.sql
  apps/hasura/seeds/masterbots/1724271332200_init_messages_seeds.sql
  apps/masterbots.ai/app/actions/dub-co.ts
  apps/masterbots.ai/app/api/og/route.tsx
  apps/masterbots.ai/app/u/[userSlug]/t/page.tsx
  apps/masterbots.ai/components/routes/bot/bot-profile-thread-section.tsx
  apps/masterbots.ai/components/routes/chat/share-button.tsx
  apps/masterbots.ai/components/routes/thread/profile-avatar.tsx
  apps/masterbots.ai/components/shared/chatbot-avatar.tsx
  apps/masterbots.ai/components/shared/feature-toggle.tsx
  apps/masterbots.ai/components/shared/og-image.tsx
  apps/masterbots.ai/lib/hooks/use-mb-chat.tsx
  apps/masterbots.ai/services/hasura/hasura.service.ts
  apps/masterbots.ai/services/hasura/hasura.service.type.ts
  packages/mb-genql/generated/schema.graphql
  packages/mb-genql/generated/schema.ts
  packages/mb-genql/generated/types.ts
Labels: bug, chore

#456 Refactor slug generation logic with improved uniqueness and type support
  apps/masterbots.ai/lib/hooks/use-mb-chat.tsx
  apps/masterbots.ai/lib/url.ts
  packages/mb-lib/src/text/text.lib.ts
Labels: bug, urgent, backend, frontend

#457 Add Sentry error monitoring and session replay integration to Next.js app
  apps/masterbots.ai/.env.example
  apps/masterbots.ai/.gitignore
  apps/masterbots.ai/app/global-error.tsx
  apps/masterbots.ai/instrumentation-client.ts
  apps/masterbots.ai/instrumentation.ts
  apps/masterbots.ai/lib/hooks/use-mb-chat.tsx
  apps/masterbots.ai/lib/sentry.ts
  apps/masterbots.ai/next.config.js
  apps/masterbots.ai/package.json
  apps/masterbots.ai/sentry.edge.config.ts
  apps/masterbots.ai/sentry.server.config.ts
  bun.lock
Labels: urgent, chore

#462 Add models table, enum type, and refactor chat message deduplication logic
  apps/hasura/metadata/databases/masterbots/tables/public_models.yaml
  apps/hasura/metadata/databases/masterbots/tables/public_models_enum.yaml
  apps/hasura/metadata/databases/masterbots/tables/tables.yaml
  apps/hasura/migrations/masterbots/1718416395664_create_table_models_enum/up.sql
  apps/hasura/migrations/masterbots/1745471202166_create_table_public_models/down.sql
  apps/hasura/migrations/masterbots/1745471202166_create_table_public_models/up.sql
  apps/hasura/seeds/masterbots/1724269974513_init_config_seeds.sql
  apps/masterbots.ai/components/routes/chat/chat-panel.tsx
  apps/masterbots.ai/components/shared/shared-accordion.tsx
  apps/masterbots.ai/lib/helpers/ai-classification.ts
  apps/masterbots.ai/lib/helpers/ai-helpers.ts
  apps/masterbots.ai/lib/hooks/use-mb-chat.tsx
Labels: bug, enhancement, urgent

#466 Feat: model selector
  apps/hasura/metadata/databases/masterbots/tables/public_models.yaml
  apps/hasura/metadata/databases/masterbots/tables/public_models_enum.yaml
  apps/masterbots.ai/app/api/chat/models/models.ts
  apps/masterbots.ai/components/routes/chat/chat-combobox.tsx
  apps/masterbots.ai/components/routes/chat/chat-model-group.tsx
  apps/masterbots.ai/lib/helpers/ai-helpers.ts
  apps/masterbots.ai/lib/hooks/use-mb-chat.tsx
  apps/masterbots.ai/lib/hooks/use-model.tsx
  apps/masterbots.ai/lib/models.tsx
  apps/masterbots.ai/services/hasura/hasura.service.ts
  apps/masterbots.ai/types/types.ts
  bun.lock
Labels: enhancement
