Repository bitcashorg/masterbots, pull requests merged in 2025-02, with the labels that each got.

#365 impr: icl metadata requests v1
  apps/hasura/seeds/masterbots/1738179716487_init_example_pt1_5.sql
  apps/masterbots.ai/app/actions/ai-main-call.ts
  apps/masterbots.ai/app/api/chat/models/models.ts
  apps/masterbots.ai/components/layout/sidebar/sidebar-link.tsx
  apps/masterbots.ai/components/layout/sidebar/sidebar.tsx
  apps/masterbots.ai/components/routes/thread/thread-popup.tsx
  apps/masterbots.ai/lib/constants/prompts.ts
  apps/masterbots.ai/lib/helpers/ai-helpers.ts
  apps/masterbots.ai/lib/hooks/use-mb-chat.ts
  apps/masterbots.ai/lib/hooks/use-power-up.tsx
  apps/masterbots.ai/lib/hooks/useSonner.tsx
  apps/masterbots.ai/services/hasura/hasura.service.ts
Labels: enhancement

#372 Fix: clickable text feature
  apps/masterbots.ai/app/globals.css
  apps/masterbots.ai/components/routes/chat/chat-clickable-text.tsx
  apps/masterbots.ai/components/routes/chat/chat-message.tsx
  apps/masterbots.ai/components/shared/shared-accordion.tsx
  apps/masterbots.ai/lib/clickable-results.ts
Labels: bug

#375 Feat: public continue thread
  apps/masterbots.ai/components/routes/browse/browse-chat-message-list.tsx
  apps/masterbots.ai/components/routes/browse/browse-chat-message.tsx
  apps/masterbots.ai/components/routes/chat/chat-clickable-text.tsx
  apps/masterbots.ai/components/routes/chat/chat-panel-header.tsx
  apps/masterbots.ai/components/routes/chat/chat-panel.tsx
  apps/masterbots.ai/components/routes/thread/thread-popup.tsx
Labels: bug, enhancement

#376 Refactor: useScroll hook
  apps/masterbots.ai/app/api/payment/intent/route.tsx
  apps/masterbots.ai/components/routes/chat/chat-accordion.tsx
  apps/masterbots.ai/components/routes/chat/chat-list.tsx
  apps/masterbots.ai/components/routes/chat/chat.tsx
  apps/masterbots.ai/components/routes/thread/thread-component.tsx
  apps/masterbots.ai/components/routes/thread/thread-popup.tsx
  apps/masterbots.ai/lib/hooks/use-debounce.tsx
  apps/masterbots.ai/lib/hooks/use-intersection-observer.tsx
  apps/masterbots.ai/lib/hooks/use-mb-scroll.tsx
  apps/masterbots.ai/lib/hooks/use-scroll.tsx
  apps/masterbots.ai/lib/hooks/use-thread.tsx
  apps/masterbots.ai/types/types.ts
  bun.lockb
Labels: bug, enhancement

#388 feat: improve clickable text with sentence content
  apps/masterbots.ai/components/routes/chat/chat-clickable-text.tsx
  apps/masterbots.ai/lib/clickable-results.ts
  apps/masterbots.ai/lib/utils.ts
  apps/masterbots.ai/types/types.ts
Labels: enhancement

#386 fix: continuous thread
  apps/masterbots.ai/app/layout.tsx
  apps/masterbots.ai/components/routes/chat/chat-list.tsx
  apps/masterbots.ai/components/routes/chat/chat-options.tsx
  apps/masterbots.ai/components/routes/thread/thread-component.tsx
  apps/masterbots.ai/components/routes/thread/user-thread-panel.tsx
  apps/masterbots.ai/components/ui/badge.tsx
  apps/masterbots.ai/lib/hooks/use-mb-chat.tsx
  apps/masterbots.ai/lib/hooks/use-thread-visibility.tsx
  apps/masterbots.ai/lib/threads.ts
  apps/masterbots.ai/services/hasura/hasura.service.ts
Labels: bug, enhancement, difficulty:medium
