Repository bitcashorg/masterbots, pull requests merged in 2025-01, with the labels that each got.

#334 New sonner
  apps/masterbots.ai/app/globals.css
  apps/masterbots.ai/app/layout.tsx
  apps/masterbots.ai/components/auth/forgot-password-form.tsx
  apps/masterbots.ai/components/auth/reset-password-form.tsx
  apps/masterbots.ai/components/auth/signup-form.tsx
  apps/masterbots.ai/components/layout/sidebar/sidebar-actions.tsx
  apps/masterbots.ai/components/routes/browse/browse-chatbot-details.tsx
  apps/masterbots.ai/components/routes/chat/chat-chatbot-details.tsx
  apps/masterbots.ai/components/routes/chat/chat-options.tsx
  apps/masterbots.ai/components/routes/chat/chat-share-dialog.tsx
  apps/masterbots.ai/components/routes/chat/new-chat.tsx
  apps/masterbots.ai/components/routes/profile/user-card.tsx
  apps/masterbots.ai/components/ui/sonner.tsx
  apps/masterbots.ai/lib/hooks/use-mb-chat.ts
  apps/masterbots.ai/lib/hooks/use-profile.tsx
  apps/masterbots.ai/lib/hooks/use-thread-visibility.tsx
  apps/masterbots.ai/lib/hooks/useSonner.tsx
  apps/masterbots.ai/package.json
  apps/masterbots.ai/tailwind.config.js
Labels: enhancement, feature

#310 impr: web search response
  apps/masterbots.ai/app/actions/ai-executers.ts
  apps/masterbots.ai/app/actions/ai-main-call.ts
  apps/masterbots.ai/components/routes/chat/chat-clickable-text.tsx
  apps/masterbots.ai/components/routes/chat/chat-message.tsx
  apps/masterbots.ai/lib/clickable-results.ts
  apps/masterbots.ai/lib/constants/prompts.ts
  apps/masterbots.ai/lib/hooks/use-mb-chat.ts
  apps/masterbots.ai/lib/utils.ts
  apps/masterbots.ai/types/types.ts
Labels: enhancement

#354 fix: init threads render + icl init cleanup
  apps/hasura/metadata/databases/masterbots/tables/.public_message.yaml.swp
  apps/hasura/metadata/databases/masterbots/tables/public_thread.yaml
  apps/masterbots.ai/app/(browse)/[category]/page.tsx
  apps/masterbots.ai/app/actions/ai-main-call.ts
  apps/masterbots.ai/app/b/[id]/page.tsx
  apps/masterbots.ai/app/c/[category]/[chatbot]/page.tsx
  apps/masterbots.ai/app/c/[category]/page.tsx
  apps/masterbots.ai/app/c/p/[category]/[expertise]/[chatbot]/page.tsx
  apps/masterbots.ai/app/c/p/page.tsx
  apps/masterbots.ai/app/c/page.tsx
  apps/masterbots.ai/app/u/[slug]/t/[category]/[chatbot]/page.tsx
  apps/masterbots.ai/components/layout/providers.tsx
  apps/masterbots.ai/components/routes/browse/browse-chat-message.tsx
  apps/masterbots.ai/components/routes/browse/browse-list.tsx
  apps/masterbots.ai/components/routes/chat/chat-chatbot-details.tsx
  apps/masterbots.ai/components/routes/chat/chat-list.tsx
  apps/masterbots.ai/components/routes/chat/chat-message.tsx
  apps/masterbots.ai/components/routes/chat/chat-panel-header.tsx
  apps/masterbots.ai/components/routes/chat/chat-search-input.tsx
  apps/masterbots.ai/components/routes/chat/chat-selected-chatbot-mobile.tsx
  apps/masterbots.ai/components/routes/chat/chat-thread-list-panel.tsx
  apps/masterbots.ai/components/routes/chat/onboarding-chatbot-details.tsx
  apps/masterbots.ai/components/routes/thread/thread-list.tsx
  apps/masterbots.ai/components/routes/thread/thread-panel.tsx
  apps/masterbots.ai/components/routes/thread/user-thread-panel.tsx
  apps/masterbots.ai/components/shared/short-message.tsx
  apps/masterbots.ai/components/shared/thread-blog-markdown.tsx
  apps/masterbots.ai/components/ui/checkbox.tsx
  apps/masterbots.ai/lib/constants/hasura.ts
  apps/masterbots.ai/lib/constants/prompts.ts
  apps/masterbots.ai/lib/hooks/use-mb-chat.ts
  apps/masterbots.ai/lib/hooks/use-sidebar.tsx
  apps/masterbots.ai/package.json
  apps/masterbots.ai/services/hasura/hasura.service.ts
  apps/masterbots.ai/types/types.ts
  bun.lockb
Labels: bug, urgent, devops, difficulty:medium, needs attention

#358 fix: downgrade react-markdown
  apps/masterbots.ai/app/u/[slug]/layout.tsx
  apps/masterbots.ai/app/u/[slug]/t/page.tsx
  apps/masterbots.ai/components/layout/profile/profile-page-sidebar.tsx
  apps/masterbots.ai/components/routes/browse/browse-chat-message.tsx
  apps/masterbots.ai/components/routes/chat/onboarding-chatbot-details.tsx
  apps/masterbots.ai/components/routes/thread/user-thread-panel.tsx
  apps/masterbots.ai/package.json
  bun.lockb
Labels: bug

#360 fix: drop and create chatbot_domain table
  apps/hasura/metadata/databases/masterbots/tables/public_chatbot_domain.yaml
  apps/hasura/metadata/databases/masterbots/tables/public_domain_enum.yaml
  apps/hasura/metadata/databases/masterbots/tables/public_gpt_chat.yaml
  apps/hasura/metadata/databases/masterbots/tables/public_label_chatbot_category.yaml
  apps/hasura/metadata/databases/masterbots/tables/public_label_chatbot_category_domain.yaml
  apps/hasura/migrations/masterbots/1738356050182_create_table_public_chatbot_domain/down.sql
  apps/hasura/migrations/masterbots/1738356050182_create_table_public_chatbot_domain/up.sql
Labels: bug, chore
